name: mikaylameyer
favicon: null
layout_spectrum: 0.75661
typography_spectrum: 0.5798
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140905'
    - '#ffffff'
    - '#613d23'
    - '#e7a265'
    - '#ffc484'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
