name: mikaylameyer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4565
title: mikaylart
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a333a'
    - '#d8c157'
    - '#a97802'
    - '#ffffff'
    - '#040700'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
